export const state = {
  token: "",
  user: null,
  profile: null,
  onboarding: null,
  onboardingOptions: null,
  home: null,
  homeAlerts: null,
  regions: [],
  collectionSummary: null,
  collectionItems: [],
  collectionDetail: null,
  collectionFilters: { search: "", variant: "", favorites_only: false, limit: 60 },
  selectedCollectionId: null,
  teamActive: null,
  teamSelection: [],
  gymsSummary: null,
  gymsItems: [],
  gymDetail: null,
  selectedGymCode: null,
  houseSummary: null,
  houseStorage: null,
  houseUpgrades: null,
  tradeSummary: null,
  tradeOffers: [],
  tradeTransactions: [],
  tradeAvailablePokemon: [],
  selectedTradeScope: "market",
  selectedTradeOfferId: null,
  shopCatalog: [],
  shopBenefits: [],
  shopPurchases: [],
  shopView: "premium",
  shopSync: { status: "idle", message: "", orderId: "" },
  rankingSummary: null,
  rankingLimit: 10,
  assetAudit: null,
  locale: "es",
  selectedStarterId: null,
  selectedStarterGeneration: "1",
  selectedAvatarCode: "steven",
};
