export const state = {
  token: "",
  user: null,
  onboarding: null,
  onboardingOptions: null,
  home: null,
  regions: [],
  collectionSummary: null,
  collectionItems: [],
  collectionDetail: null,
  collectionFilters: { search: "", variant: "", favorites_only: false, limit: 60 },
  selectedCollectionId: null,
  teamActive: null,
  teamSelection: [],
  gymsSummary: null,
  gymsItems: [],
  gymDetail: null,
  selectedGymCode: null,
  locale: "es",
  selectedStarterId: null,
  selectedStarterGeneration: "1",
  selectedAvatarCode: "steven",
};
